<?php

require 'vendor/autoload.php';
use Minishlink\WebPush\WebPush;

$endpoint = 'https://fcm.googleapis.com/fcm/send/f-LGaZcXqiY:APA91bGOovnIY4q27axfyt1MFOw2UM2SQKKGuiR8h3uZ0wjSsZ-neMZecbYMvZY5sJXuZ0UcsYuSpznWDc4qPZh9fB6r5eHZDuezo_nvzr0yX7YbYI57VrS28echDb_GXLNaFD0lp5Ya'; // Chrome

$auth = array(
    'VAPID' => array(
        'subject' => NULL, // can be a mailto: or your website address
        'publicKey' => 'YOUR PUBLIC KEY', // (recommended) uncompressed public key P-256 encoded in Base64-URL
        'privateKey' => 'YOUR PRIVATE KEY', // (recommended) in fact the secret multiplier of the private key encoded in Base64-URL
    ),
);

// array of notifications
$notifications = array(
    array(
        'endpoint' => 'https://updates.push.services.mozilla.com/wpush/v1/gAAAAABYxDiJRX5ADcvdZq_Suh7EUZu-3CJ3JdgmmWWB7rl8SU_uYHG_g7LTDHOTlWle7BWVDvCv92baL5bBSC_Hktv6rOAR09gG3LiG67SisLnwOurZ_E3XElDKQwKAFrdGRo9uos0G', // Firefox 43+
        'payload' => 'teste push firefox',
        'userPublicKey' => 'YOUR PUBLIC KEY GENERATED BY THE JSON', // base 64 encoded, should be 88 chars
        'userAuthToken' => 'YOUR AUTH TOKEN GENERATED BY THE JSON', // base 64 encoded, should be 24 chars
    ),
    array(
    'endpoint' => $endpoint, // Chrome
    'payload' => 'teste chrome',
    'userPublicKey' => 'YOUR PUBLIC KEY GENERATED BY THE JSON',
    'userAuthToken' => 'YOUR AUTH TOKEN GENERATED BY THE JSON',
));

$webPush = new WebPush($auth);

// send multiple notifications with payload
foreach ($notifications as $notification) {
    $webPush->sendNotification(
			$notification['endpoint'],
			$notification['payload'], // optional (defaults null)
			$notification['userPublicKey'], // optional (defaults null)
			$notification['userAuthToken'] // optional (defaults null),
		);
}
$webPush->flush();
